{{define "nginx.conf"}}
# Generated by MyNginx

user {{.User}};

pid {{.PID}};

worker_processes {{.WorkerProcesses}};

events {
    worker_connections 768;
    # multi_accept on;
}

http {

    sendfile {{.HTTP.Sendfile}};

    tcp_nopush {{.HTTP.TCPNoPush}};

    types_hash_max_size {{.HTTP.TypesHashMaxSize}};

    server_tokens {{.HTTP.ServerToken}};

    server_names_hash_bucket_size {{.HTTP.ServerNamesHashBucketSize}};

    server_name_in_redirect {{.HTTP.ServerNameInRedirect}};

    default_type {{.HTTP.DefaultType}};

    ssl_protocols {{.HTTP.SSLProtocols}}; # Dropping SSLv3, ref: POODLE

    ssl_prefer_server_ciphers {{.HTTP.SSLPreferServerCiphers}};

    access_log {{.HTTP.AccessLog}};

    error_log {{.HTTP.ErrorLog}};

    gzip {{.HTTP.GZip}};

    gzip_vary {{.HTTP.GZipVary}};

    gzip_proxied {{.HTTP.GZipProxied}};

    gzip_comp_level {{.HTTP.GZipCompLevel}};

    gzip_buffers {{.HTTP.GZipBuffers}};

    gzip_http_version {{.HTTP.GZipHTTPVersion}};

    gzip_types {{.HTTP.GZipTypes}};
    {{ range .HTTP.Servers}}
    server {
        {{range .Listens}}
        listen {{.}};
        {{end}}
        server_name {{.ServerName}};

        root {{.Root}};

        index {{.Index}};
        {{range .Locations}}
        location / {
            deny {{.Deny}};

            proxy_pass {{.ProxyPass}};

            fastcgi_pass {{.FastCGIPass}};
        }
        {{end}}
    }
    {{end}}
}
{{end}}